'use client'

import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ChevronLeft, ChevronRight, ExternalLink } from 'lucide-react'
import LetterHtmlDocument from '@/app/components/letter-of-consent/LetterHtmlDocument'
import LetterOfConsentBackendPreview from '@/app/components/letter-of-consent/LetterOfConsentBackendPreview'
import { LoadingCentered } from '@/app/components/LoadingSpinner'

type Submission = {
  id: string
  status: string
  companyId: number
  companyName?: string
  senderId?: string
  networks: string[]
  submittedAt: string
  registrationDocumentUrl?: string
  signatureImageUrl?: string
  profileImageUrl?: string
  email?: string
  phoneNumber?: string
  physicalAddress?: string
  industry?: string
  description?: string
  websiteUrl?: string
  /** SMS samples generated by backend (Brutus) and stored with the submission */
  letterSmsSamples?: string[]
  letterGenerationError?: string
  /** Server-rendered letter HTML when persisted with the submission */
  letterHtml?: string | null
  reviewMessage?: string
  reviewAttachments?: string[]
  reviewedByReviewerId?: number
  reviewedAt?: string
}

function docKindFromUrl(url: string): 'pdf' | 'image' {
  const base = url.split('?')[0]?.toLowerCase() ?? ''
  if (/\.(png|jpg|jpeg|gif|webp|svg)$/.test(base)) return 'image'
  return 'pdf'
}

function DocCard({
  title,
  url,
  kind,
}: {
  title: string
  url?: string
  kind: 'pdf' | 'image'
}) {
  if (!url) {
    return (
      <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/80 p-4">
        <p className="text-sm font-medium text-slate-700">{title}</p>
        <p className="mt-1 text-xs text-slate-500">Not provided</p>
      </div>
    )
  }
  return (
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-slate-100 px-4 py-2">
        <p className="text-sm font-semibold text-slate-800">{title}</p>
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-xs font-medium text-sky-600 hover:underline"
        >
          Open <ExternalLink className="h-3 w-3" />
        </a>
      </div>
      <div className="h-[360px] bg-slate-50 sm:h-[440px] lg:h-[560px]">
        {kind === 'image' ? (
          // eslint-disable-next-line @next/next/no-img-element -- external MNO URLs
          <img src={url} alt="" className="h-full w-full object-contain" />
        ) : (
          <iframe title={title} src={url} className="h-full w-full bg-white" />
        )}
      </div>
    </div>
  )
}

export default function MtnReviewSubmissionDetailPage() {
  const params = useParams()
  const router = useRouter()
  const id = typeof params.id === 'string' ? params.id : ''
  const [row, setRow] = useState<Submission | null>(null)
  const [error, setError] = useState('')
  const [actionLoading, setActionLoading] = useState(false)
  const [activeSlideIndex, setActiveSlideIndex] = useState(0)
  const [reviewMessageDraft, setReviewMessageDraft] = useState('')
  const [reviewUploadFiles, setReviewUploadFiles] = useState<File[]>([])
  const [showRequestChangesModal, setShowRequestChangesModal] = useState(false)

  const load = useCallback(() => {
    if (!id) return
    void fetch(`/api/mtn-review/submissions/${id}`)
      .then((r) => {
        if (r.status === 404) {
          setError('Submission not found.')
          return null
        }
        if (!r.ok) throw new Error('load')
        return r.json()
      })
      .then((data: { submission?: Submission } | null) => {
        if (data?.submission) setRow(data.submission)
      })
      .catch(() => setError('Failed to load submission.'))
  }, [id])

  useEffect(() => {
    load()
  }, [load])

  const patchStatus = async (
    status: 'accepted' | 'withdrawn' | 'pending' | 'request_changes',
    options?: { message?: string; files?: string[] },
  ) => {
    if (!id) return
    setActionLoading(true)
    setError('')
    try {
      const res = await fetch(`/api/mtn-review/submissions/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          status,
          message: options?.message,
          files: options?.files,
        }),
      })
      if (!res.ok) throw new Error('patch')
      const data = await res.json()
      if (data.submission) setRow(data.submission)
      if (status === 'request_changes') {
        setReviewMessageDraft('')
        setReviewUploadFiles([])
        setShowRequestChangesModal(false)
      }
      router.refresh()
    } catch {
      setError('Action failed.')
    } finally {
      setActionLoading(false)
    }
  }

  const pending = row?.status === 'pending'
  const canMoveToPending = row?.status === 'accepted' || row?.status === 'withdrawn' || row?.status === 'request_changes'
  const documents = useMemo(
    () =>
      row
        ? [
            {
              id: 'registration',
              title: 'Registration document',
              url: row.registrationDocumentUrl,
              kind: row.registrationDocumentUrl ? docKindFromUrl(row.registrationDocumentUrl) : 'pdf',
            },
            {
              id: 'signature',
              title: 'Signature (authorized signatory)',
              url: row.signatureImageUrl,
              kind: 'image' as const,
            },
            {
              id: 'profile',
              title: 'Company logo / profile',
              url: row.profileImageUrl,
              kind: 'image' as const,
            },
          ].filter((doc) => Boolean(doc.url))
        : [],
    [row],
  )
  const slides = useMemo(
    () => [
      {
        id: 'letter-consent',
        title: 'Letter / consent',
        type: 'letter' as const,
      },
      ...documents.map((doc) => ({
        id: `document-${doc.id}`,
        title: doc.title,
        type: 'document' as const,
        doc,
      })),
    ],
    [documents],
  )
  const currentSlide = slides[activeSlideIndex] ?? null

  useEffect(() => {
    if (slides.length === 0) {
      setActiveSlideIndex(0)
      return
    }
    setActiveSlideIndex((prev) => Math.min(prev, slides.length - 1))
  }, [slides.length])

  if (error && !row) {
    return (
      <div className="space-y-4">
        <Link
          href="/mtn-review/submissions"
          className="inline-flex items-center gap-1 text-sm font-medium text-sky-600 hover:underline"
        >
          <ArrowLeft className="h-4 w-4" /> Back to submissions
        </Link>
        <p className="text-red-700">{error}</p>
      </div>
    )
  }

  if (!row) {
    return <LoadingCentered minHeight={240} label="Loading submission" />
  }

  const letterGenerationError = row.letterGenerationError
  const showStoredLetterHtml = Boolean(row.letterHtml)
  const reviewAttachments = row.reviewAttachments ?? []

  const uploadReviewFiles = async (files: File[]): Promise<string[]> => {
    if (files.length === 0) return []
    const formData = new FormData()
    files.forEach((file) => formData.append('files', file))

    const res = await fetch('/api/mtn-review/attachments', {
      method: 'POST',
      body: formData,
    })
    const data = (await res.json().catch(() => null)) as
      | { error?: string; files?: Array<{ url?: string }> }
      | null
    if (!res.ok) {
      throw new Error(data?.error || 'Failed to upload attachments.')
    }

    return (data?.files ?? []).map((x) => x.url).filter((x): x is string => Boolean(x))
  }

  return (
    <div className="space-y-8">
      <div>
        <Link
          href="/mtn-review/submissions"
          className="inline-flex items-center gap-1 text-sm font-medium text-sky-600 hover:underline"
        >
          <ArrowLeft className="h-4 w-4" /> Submissions
        </Link>
        <div className="mt-4 flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">
              {row.companyName ?? 'Unknown company'}
            </h1>
            <p className="mt-1 text-sm text-slate-600">
              Sender ID: <span className="font-mono font-medium">{row.senderId ?? '—'}</span> ·
              Submitted {new Date(row.submittedAt).toLocaleString()}
            </p>
            <p className="mt-1 text-xs text-slate-500">
              Status:{' '}
              <span className="font-semibold capitalize text-slate-800">{row.status}</span>
            </p>
          </div>
          {pending ? (
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => void patchStatus('accepted')}
                className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-700 disabled:opacity-50"
              >
                Accept
              </button>
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => setShowRequestChangesModal(true)}
                className="rounded-xl bg-amber-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-amber-700 disabled:opacity-50"
              >
                Request changes
              </button>
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => void patchStatus('withdrawn')}
                className="rounded-xl border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-800 hover:bg-slate-50 disabled:opacity-50"
              >
                Withdraw
              </button>
            </div>
          ) : canMoveToPending ? (
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => void patchStatus('pending')}
                className="rounded-xl border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-800 hover:bg-slate-50 disabled:opacity-50"
              >
                Move back to pending
              </button>
            </div>
          ) : null}
        </div>
      </div>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          Review notes
        </h2>

        {row.reviewedAt ? (
          <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2 text-sm text-slate-700">
            <p>
              Last reviewed:{' '}
              <span className="font-medium">{new Date(row.reviewedAt).toLocaleString()}</span>
            </p>
            {row.reviewMessage ? (
              <p className="whitespace-pre-wrap text-slate-800">{row.reviewMessage}</p>
            ) : null}
            {reviewAttachments.length > 0 ? (
              <div className="space-y-1">
                <p className="font-medium text-slate-800">Attachments</p>
                <ul className="list-disc pl-5 space-y-1">
                  {reviewAttachments.map((item) => (
                    <li key={item}>
                      <a
                        href={item}
                        target="_blank"
                        rel="noreferrer"
                        className="text-sky-700 hover:underline break-all"
                      >
                        {item}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </div>
        ) : (
          <p className="text-sm text-slate-500">No reviewer note yet.</p>
        )}

      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          Company details
        </h2>

        <dl className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200">
          <div className="grid gap-2 px-4 py-3 sm:grid-cols-[180px_minmax(0,1fr)] sm:items-center">
            <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Industry</dt>
            <dd className="text-sm font-medium text-slate-900">{row.industry ?? '—'}</dd>
          </div>
          <div className="grid gap-2 px-4 py-3 sm:grid-cols-[180px_minmax(0,1fr)] sm:items-center">
            <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Email</dt>
            <dd className="text-sm font-medium text-slate-900 break-words">
              {row.email ? (
                <a className="text-sky-700 hover:underline" href={`mailto:${row.email}`}>
                  {row.email}
                </a>
              ) : (
                '—'
              )}
            </dd>
          </div>
          <div className="grid gap-2 px-4 py-3 sm:grid-cols-[180px_minmax(0,1fr)] sm:items-center">
            <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Phone</dt>
            <dd className="text-sm font-medium text-slate-900">
              {row.phoneNumber ? (
                <a className="text-sky-700 hover:underline" href={`tel:${row.phoneNumber}`}>
                  {row.phoneNumber}
                </a>
              ) : (
                '—'
              )}
            </dd>
          </div>
          <div className="grid gap-2 px-4 py-3 sm:grid-cols-[180px_minmax(0,1fr)] sm:items-start">
            <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Address</dt>
            <dd className="text-sm font-medium text-slate-900">{row.physicalAddress ?? '—'}</dd>
          </div>
          <div className="grid gap-2 px-4 py-3 sm:grid-cols-[180px_minmax(0,1fr)] sm:items-center">
            <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Website</dt>
            <dd className="text-sm font-medium text-slate-900 break-all">
              {row.websiteUrl ? (
                <a href={row.websiteUrl} className="text-sky-700 hover:underline" target="_blank" rel="noreferrer">
                  {row.websiteUrl}
                </a>
              ) : (
                '—'
              )}
            </dd>
          </div>
          <div className="grid gap-2 px-4 py-3 sm:grid-cols-[180px_minmax(0,1fr)] sm:items-center">
            <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Networks</dt>
            <dd className="text-sm font-medium text-slate-900">
              {row.networks?.length ? row.networks.join(', ') : '—'}
            </dd>
          </div>
        </dl>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="space-y-4 pt-1">
          <p className="text-xs text-slate-600">
            Review attached documents and generated consent letter before taking action.
          </p>

          {currentSlide?.type === 'document' ? (
            <DocCard
              title={currentSlide.doc.title}
              url={currentSlide.doc.url}
              kind={currentSlide.doc.kind}
            />
          ) : (
            <div className="space-y-3">
              <p className="text-xs text-slate-600">
                Formal letter generated from submitted company details. Recipient and body adapt
                to the primary selected MNO (first network on the submission).
              </p>
              {letterGenerationError ? (
                <p className="text-xs text-amber-800">
                  Letter samples were not generated automatically ({letterGenerationError}). The
                  preview may use placeholder SMS lines.
                </p>
              ) : null}
              {showStoredLetterHtml ? (
                <LetterHtmlDocument html={row.letterHtml ?? ''} />
              ) : (
                <LetterOfConsentBackendPreview
                  payload={{
                    companyId: row.companyId,
                    companyName: row.companyName,
                    senderId: row.senderId,
                    networks: row.networks?.length ? row.networks : ['Mtn'],
                    physicalAddress: row.physicalAddress,
                    phoneNumber: row.phoneNumber,
                    email: row.email,
                    websiteUrl: row.websiteUrl,
                    description: row.description,
                    industry: row.industry,
                    submittedAt: row.submittedAt,
                  }}
                />
              )}
            </div>
          )}

          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="text-xs text-slate-500">
              Item {activeSlideIndex + 1} of {slides.length}: {currentSlide?.title ?? '—'}
            </div>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() =>
                  setActiveSlideIndex((prev) => (prev - 1 + slides.length) % slides.length)
                }
                disabled={slides.length <= 1}
                className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 transition hover:border-sky-300 hover:text-sky-700 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <ChevronLeft className="h-3.5 w-3.5" />
                Prev
              </button>
              <button
                type="button"
                onClick={() => setActiveSlideIndex((prev) => (prev + 1) % slides.length)}
                disabled={slides.length <= 1}
                className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 transition hover:border-sky-300 hover:text-sky-700 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Next
                <ChevronRight className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>

          {slides.length > 1 ? (
            <div className="flex items-center gap-2">
              {slides.map((slide, idx) => {
                const active = idx === activeSlideIndex
                return (
                  <button
                    key={slide.id}
                    type="button"
                    onClick={() => setActiveSlideIndex(idx)}
                    aria-label={`View ${slide.title}`}
                    className={`h-2.5 w-2.5 rounded-full transition ${
                      active ? 'bg-sky-600' : 'bg-slate-300 hover:bg-slate-400'
                    }`}
                  />
                )
              })}
            </div>
          ) : null}
        </div>
      </section>

      {showRequestChangesModal ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4">
          <div className="w-full max-w-2xl rounded-2xl border border-amber-200 bg-white p-5 shadow-xl space-y-3">
            <div className="flex items-center justify-between gap-3">
              <h3 className="text-base font-semibold text-amber-900">Request changes from submitter</h3>
              <button
                type="button"
                onClick={() => setShowRequestChangesModal(false)}
                disabled={actionLoading}
                className="rounded-lg border border-slate-300 px-2.5 py-1 text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
              >
                Close
              </button>
            </div>
            <textarea
              value={reviewMessageDraft}
              onChange={(e) => setReviewMessageDraft(e.target.value)}
              rows={5}
              className="w-full rounded-lg border border-amber-300 bg-white px-3 py-2 text-sm text-slate-900"
              placeholder="Enter review comments for requested changes"
            />
            <div className="space-y-2">
              <label className="block text-xs font-semibold uppercase tracking-wide text-slate-600">
                Upload files (optional)
              </label>
              <input
                type="file"
                multiple
                onChange={(e) => setReviewUploadFiles(Array.from(e.target.files ?? []))}
                className="block w-full text-sm text-slate-700 file:mr-3 file:rounded-lg file:border file:border-amber-300 file:bg-white file:px-3 file:py-2 file:text-sm file:font-medium file:text-slate-700 hover:file:bg-amber-100"
              />
              {reviewUploadFiles.length > 0 ? (
                <ul className="list-disc pl-5 text-xs text-slate-700 space-y-1">
                  {reviewUploadFiles.map((file) => (
                    <li key={`${file.name}-${file.size}`}>{file.name}</li>
                  ))}
                </ul>
              ) : null}
            </div>
            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setShowRequestChangesModal(false)}
                disabled={actionLoading}
                className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 hover:bg-slate-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => {
                  void (async () => {
                    try {
                      const uploadedUrls = await uploadReviewFiles(reviewUploadFiles)
                      await patchStatus('request_changes', {
                        message: reviewMessageDraft,
                        files: uploadedUrls,
                      })
                    } catch (uploadError) {
                      setError(uploadError instanceof Error ? uploadError.message : 'File upload failed.')
                    }
                  })()
                }}
                className="rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700 disabled:opacity-50"
              >
                Request changes
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}
