'use client'

import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, ExternalLink } from 'lucide-react'
import LetterHtmlDocument from '@/app/components/letter-of-consent/LetterHtmlDocument'
import LetterOfConsentBackendPreview from '@/app/components/letter-of-consent/LetterOfConsentBackendPreview'

type Submission = {
  id: string
  status: string
  companyId: number
  companyName?: string
  senderId?: string
  networks: string[]
  submittedAt: string
  registrationDocumentUrl?: string
  signatureImageUrl?: string
  profileImageUrl?: string
  email?: string
  phoneNumber?: string
  physicalAddress?: string
  industry?: string
  description?: string
  websiteUrl?: string
  /** SMS samples generated by backend (Brutus) and stored with the submission */
  letterSmsSamples?: string[]
  letterGenerationError?: string
  /** Server-rendered letter HTML when persisted with the submission */
  letterHtml?: string | null
}

function docKindFromUrl(url: string): 'pdf' | 'image' {
  const base = url.split('?')[0]?.toLowerCase() ?? ''
  if (/\.(png|jpg|jpeg|gif|webp|svg)$/.test(base)) return 'image'
  return 'pdf'
}

function DocCard({
  title,
  url,
  kind,
}: {
  title: string
  url?: string
  kind: 'pdf' | 'image'
}) {
  if (!url) {
    return (
      <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/80 p-4">
        <p className="text-sm font-medium text-slate-700">{title}</p>
        <p className="mt-1 text-xs text-slate-500">Not provided</p>
      </div>
    )
  }
  return (
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-slate-100 px-4 py-2">
        <p className="text-sm font-semibold text-slate-800">{title}</p>
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-xs font-medium text-sky-600 hover:underline"
        >
          Open <ExternalLink className="h-3 w-3" />
        </a>
      </div>
      <div className="h-64 bg-slate-50">
        {kind === 'image' ? (
          // eslint-disable-next-line @next/next/no-img-element -- external MNO URLs
          <img src={url} alt="" className="h-full w-full object-contain" />
        ) : (
          <iframe title={title} src={url} className="h-full w-full bg-white" />
        )}
      </div>
    </div>
  )
}

export default function MtnReviewSubmissionDetailPage() {
  const params = useParams()
  const router = useRouter()
  const id = typeof params.id === 'string' ? params.id : ''
  const [row, setRow] = useState<Submission | null>(null)
  const [error, setError] = useState('')
  const [actionLoading, setActionLoading] = useState(false)

  const load = useCallback(() => {
    if (!id) return
    void fetch(`/api/mtn-review/submissions/${id}`)
      .then((r) => {
        if (r.status === 404) {
          setError('Submission not found.')
          return null
        }
        if (!r.ok) throw new Error('load')
        return r.json()
      })
      .then((data: { submission?: Submission } | null) => {
        if (data?.submission) setRow(data.submission)
      })
      .catch(() => setError('Failed to load submission.'))
  }, [id])

  useEffect(() => {
    load()
  }, [load])

  const patchStatus = async (status: 'accepted' | 'withdrawn') => {
    if (!id) return
    setActionLoading(true)
    try {
      const res = await fetch(`/api/mtn-review/submissions/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status }),
      })
      if (!res.ok) throw new Error('patch')
      const data = await res.json()
      if (data.submission) setRow(data.submission)
      router.refresh()
    } catch {
      setError('Action failed.')
    } finally {
      setActionLoading(false)
    }
  }

  if (error && !row) {
    return (
      <div className="space-y-4">
        <Link
          href="/mtn-review/submissions"
          className="inline-flex items-center gap-1 text-sm font-medium text-sky-600 hover:underline"
        >
          <ArrowLeft className="h-4 w-4" /> Back to submissions
        </Link>
        <p className="text-red-700">{error}</p>
      </div>
    )
  }

  if (!row) {
    return <p className="text-sm text-slate-600">Loading…</p>
  }

  const pending = row.status === 'pending'

  return (
    <div className="space-y-8">
      <div>
        <Link
          href="/mtn-review/submissions"
          className="inline-flex items-center gap-1 text-sm font-medium text-sky-600 hover:underline"
        >
          <ArrowLeft className="h-4 w-4" /> Submissions
        </Link>
        <div className="mt-4 flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">
              {row.companyName ?? 'Unknown company'}
            </h1>
            <p className="mt-1 text-sm text-slate-600">
              Sender ID: <span className="font-mono font-medium">{row.senderId ?? '—'}</span> ·
              Submitted {new Date(row.submittedAt).toLocaleString()}
            </p>
            <p className="mt-1 text-xs text-slate-500">
              Status:{' '}
              <span className="font-semibold capitalize text-slate-800">{row.status}</span>
            </p>
          </div>
          {pending ? (
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => void patchStatus('accepted')}
                className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-700 disabled:opacity-50"
              >
                Accept
              </button>
              <button
                type="button"
                disabled={actionLoading}
                onClick={() => void patchStatus('withdrawn')}
                className="rounded-xl border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-800 hover:bg-slate-50 disabled:opacity-50"
              >
                Withdraw
              </button>
            </div>
          ) : null}
        </div>
      </div>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          Company details
        </h2>
        <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">
          <div>
            <dt className="text-slate-500">Industry</dt>
            <dd className="font-medium text-slate-900">{row.industry ?? '—'}</dd>
          </div>
          <div>
            <dt className="text-slate-500">Email</dt>
            <dd className="font-medium text-slate-900">{row.email ?? '—'}</dd>
          </div>
          <div>
            <dt className="text-slate-500">Phone</dt>
            <dd className="font-medium text-slate-900">{row.phoneNumber ?? '—'}</dd>
          </div>
          <div className="sm:col-span-2">
            <dt className="text-slate-500">Address</dt>
            <dd className="font-medium text-slate-900">{row.physicalAddress ?? '—'}</dd>
          </div>
          <div className="sm:col-span-2">
            <dt className="text-slate-500">Website</dt>
            <dd className="font-medium text-slate-900">
              {row.websiteUrl ? (
                <a href={row.websiteUrl} className="text-sky-600 hover:underline" target="_blank" rel="noreferrer">
                  {row.websiteUrl}
                </a>
              ) : (
                '—'
              )}
            </dd>
          </div>
        </dl>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          Uploaded documents
        </h2>
        <div className="grid gap-4 lg:grid-cols-2">
          <DocCard
            title="Registration document"
            url={row.registrationDocumentUrl}
            kind={
              row.registrationDocumentUrl
                ? docKindFromUrl(row.registrationDocumentUrl)
                : 'pdf'
            }
          />
          <DocCard title="Signature (authorized signatory)" url={row.signatureImageUrl} kind="image" />
          {row.profileImageUrl ? (
            <DocCard title="Company logo / profile" url={row.profileImageUrl} kind="image" />
          ) : null}
        </div>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-slate-50/80 p-6 shadow-sm">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          Letter / consent
        </h2>
        <p className="mt-2 text-xs text-slate-600">
          Formal letter generated from submitted company details. Recipient and body adapt to the
          primary selected MNO (first network on the submission).
        </p>
        <div className="mt-4 space-y-2">
          {row.letterGenerationError ? (
            <p className="text-xs text-amber-800">
              Letter samples were not generated automatically ({row.letterGenerationError}). The
              preview may use placeholder SMS lines.
            </p>
          ) : null}
          {row.letterHtml ? (
            <LetterHtmlDocument html={row.letterHtml} fileNamePrefix={row.id} />
          ) : (
            <LetterOfConsentBackendPreview
              payload={{
                companyId: row.companyId,
                companyName: row.companyName,
                senderId: row.senderId,
                networks: row.networks?.length ? row.networks : ['Mtn'],
                physicalAddress: row.physicalAddress,
                phoneNumber: row.phoneNumber,
                email: row.email,
                websiteUrl: row.websiteUrl,
                description: row.description,
                industry: row.industry,
                submittedAt: row.submittedAt,
              }}
              downloadFileNamePrefix={row.id}
            />
          )}
        </div>
      </section>
    </div>
  )
}
